### ISSUE TITLE
Grauer Rahmen um Filter

### ISSUE THREAD

**Issue by math-GH** [heimseiten/contao-dark-mode-backend-bundle#2]
Soll der graue Rahmen so sein?
Seite: Seitenstruktur.

Der Rahmen wird erst mit dem Dark-Mode hinzugefügt.
![grafik](https://user-images.githubusercontent.com/1645099/103417556-67445180-4b8b-11eb-85db-47952d10901d.png)

**Comment by heimseiten** [comment]
Danke! Wurde in Version 1.3.3 behoben.

**Comment by heimseiten** [comment]
Danke! Wurde in Version 1.3.3 behoben.
