### ISSUE TITLE
Hintergrundfarbe links unten

### ISSUE THREAD

**Issue by math-GH** [heimseiten/contao-dark-mode-backend-bundle#3]
Ich finde es ziemlich cool gelöst, dass im Darkmode die Hintergrundfarbe identisch zum aktiven Backend-Modul ist. Das ergibt optisch eine sehr gute Einheit und ist logisch.

Jedoch ist links unten die Contao-Versionsangabe in der gleichen Farbe.

Könnte links unten nicht eine etwas andere Hintergrundfarbe erhalten? Vielleicht etwas dunkler. So würde eine Kante zum Content entstehen, die das optisch gut trennt.

![grafik](https://user-images.githubusercontent.com/1645099/103418180-db7ff480-4b8d-11eb-9198-48000db985d3.png)

**Comment by heimseiten** [comment]
Wurde in 1.3.4 geändert.
