### ISSUE TITLE
Mouseover title fehlt

### ISSUE THREAD

**Issue by math-GH** [heimseiten/contao-dark-mode-backend-bundle#4]
Hier fehlt der Mouseover-Title, damit der Nutzer die coole Funktion erkennt:
![grafik](https://user-images.githubusercontent.com/1645099/103418289-51845b80-4b8e-11eb-9bac-d28745cc0584.png)

Die Glocke daneben kann das:
![grafik](https://user-images.githubusercontent.com/1645099/103418325-6f51c080-4b8e-11eb-8bc5-07dffdfe44ab.png)

**Comment by heimseiten** [comment]
Ich weiß leider spontan nicht, wie die Tooltips aktiviert werden. Der Hintergrund der Schalfläche wird ab der Version 1.3.5 bei Mouseover geändert.

**Comment by mathContao** [comment]
eventuell so?
![grafik](https://user-images.githubusercontent.com/1645099/103480791-a7e3db00-4dd6-11eb-88dc-e64b9f91faac.png)
https://docs.contao.org/dev/guides/back-end-routes/

**Comment by math-GH** [comment]
das title-Attribut muss auf das a bzw. span gesetzt werden (nicht auf li).

Und dann mit
```  
new Tips.Contao($$('#tmenu a[title]').filter(function(i) {
			return i.title != '';
		}), {
			offset: {x:9, y:42}
		})
```

nochmal das Tooltips-Crawling starten.

(siehe Zeile 1199 in https://github.com/contao/contao/blob/de175e4dbe8f183bf685be3fe1ba8a8dad8dfb4a/core-bundle/src/Resources/public/core.js)


Mit der sehr heißen Nadel gestrickt sieht das so aus:
![grafik](https://user-images.githubusercontent.com/1645099/103482888-c9978f00-4de3-11eb-9a66-2c86a34044dc.png)

![grafik](https://user-images.githubusercontent.com/1645099/103482903-e0d67c80-4de3-11eb-95c0-ea53dcf7ec16.png)

**Comment by heimseiten** [comment]
Super, danke! Wurde in der Version 1.3.5 hinzugefügt.
