### ISSUE TITLE
Uncaught TypeError in der Dateiverwaltung

### ISSUE THREAD

**Issue by math-GH** [heimseiten/contao-dark-mode-backend-bundle#5]
Contao 4.9

Klickpfad:
1) Dateiverwaltung öffnen
2) auf Info klicken (das Modal-Fenster öffnet sich)
3) die Fehlermeldung im Firefox erscheint
![grafik](https://user-images.githubusercontent.com/1645099/104818395-a4fdd700-5827-11eb-95f2-7f69bc11944e.png)

(Firefox 84)

**Comment by heimseiten** [comment]
Wurde in Version 1.3.9 korrigiert.
