### ISSUE TITLE
CSS: tl_header

### ISSUE THREAD

**Issue by math-GH** [heimseiten/contao-dark-mode-backend-bundle#6]
die Umfärbung von der Klasse tl_header scheint in der Traversierung sehr umständlich und sehr speziell zu sein:

![grafik](https://user-images.githubusercontent.com/1645099/104847475-84de1e80-58e0-11eb-85c0-cf4992d3aa33.png)

Würde ein Überschreiben von ".tl_header" (ohne #main ..... .parent_view) nicht auch ausreichen?

**Comment by heimseiten** [comment]
Könnte ohne weiteres umgestellt werden. Gäbe es dabei einen Vorteil? So wie es jetzt ist, steht es in der scss-Datei an der Stelle, wo das Element auch auftaucht, sodass man es im Context der umliegenden Elemente sehen kann.

**Comment by math-GH** [comment]
Ich kann die scss-Dateien von Contao gerade nicht finden bzw. ich weiß nicht wo sie liegen. In der (zusammengefassten) CSS-Datei sieht es so aus:
![grafik](https://user-images.githubusercontent.com/1645099/104965285-b1786000-59de-11eb-88d3-493eba9570b8.png)

Einen kleinen Vorteil hätte meine Erweiterun be_piwikcharts. Denn da nutze ich die Standardkomponenten in der light Version (bei der ich auf das ganze Listen-Drumherum-Div verzichte, weil es keine Liste ist).
![grafik](https://user-images.githubusercontent.com/1645099/104965423-f9978280-59de-11eb-94c8-c224341f4104.png)
Ist natürlich kein wichtiges Argument. Da ist es mir jedoch aufgefallen.

**Comment by heimseiten** [comment]
Wurde in Version 1.3.13 korrigiert. Passt das so für Deine Erweiterung?

**Comment by math-GH** [comment]
Ich liebe es <3 Vielen Dank!
