### ISSUE TITLE
Einfärbung: Weiterleitungsseite Auswahl

### ISSUE THREAD

**Issue by math-GH** [heimseiten/contao-dark-mode-backend-bundle#7]
Im Modal-Fenster zur Auswahl der Weiterleitungsseite (z.B. Nachrichten-Archiv):

![grafik](https://user-images.githubusercontent.com/1645099/104847588-367d4f80-58e1-11eb-9fa6-44ade9f49b44.png)

1) Die Schrift des Reiters ist schwer lesbar (graue Schrift auf grauen Grund)
2) die Radio-Buttons haben keinen dunklen Hintergrund (so wie am Ende der Liste)

**Comment by heimseiten** [comment]
Wurde in Version 1.3.8 korrigiert.
