### ISSUE TITLE
Dataiverwaltung: grauer Rahmen um Icon zum verschieben der Einträge

### ISSUE THREAD

**Issue by math-GH** [heimseiten/contao-dark-mode-backend-bundle#8]
Ein grauer Rahmen ist in der Dateiverwaltung noch verblieben (Icon: Elemente verschieben)

![grafik](https://user-images.githubusercontent.com/1645099/104847653-a8559900-58e1-11eb-940d-b2ad88ab5b95.png)

**Comment by heimseiten** [comment]
Wurde in Version 1.3.7 korrigiert.
